build_mode = "release"
target_adapters = []
target_platforms = [
    "ios",
    "android",
]
ios = [
    "aarch64-apple-ios-sim",
    "aarch64-apple-ios",
]
android = [
    "aarch64-linux-android",
    "x86_64-linux-android",
]
auto_update = true
